nodeLinker: hoisted
allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@55.0.33'
  - '@expo/config@55.0.18'
  - '@expo/local-build-cache-provider@55.0.14'
  - '@expo/metro-config@55.0.24'
  - '@expo/prebuild-config@55.0.19'
  - babel-preset-expo@55.0.23
  - expo-file-system@55.0.23
  - expo@55.0.27
  - expo-audio@55.0.15
  - expo-crypto@55.0.16
  - expo-device@55.0.18
  - expo-linking@55.0.16
  - expo-secure-store@55.0.15
  - expo-splash-screen@55.0.22
  - expo-system-ui@55.0.19
  - expo-web-browser@55.0.17
  - expo-linear-gradient@55.0.15
patchedDependencies:
  expo-audio: patches/expo-audio.patch
