name: Feature request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: Describe the feature or improvement.
    validations:
      required: true
