name: Feature request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Description
      description: Describe the feature or improvement you'd like.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like it to work? E.g. where in the app you'd expect to find it, or another app that does it well.
    validations:
      required: false
