name: Feature request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Description
      description: Describe the feature or improvement you'd like.
    validations:
      required: true
